이미지 조합 함수 구현
prography-TEAM-4/TEAM_4_backend pull request #143
Opened 2022-07-11 13:29 UTC by lcomment

2022-07-12 05:10 UTC, be-student requested changes

2022-07-12 05:10 UTC, be-student commented on src/commom/utility/generateImageCode.ts
> +  const kindOfImg: number[] = Array.from(set);
몰라서 그러는데, Array.from(set) 하면 무조건 정렬 된 순서로 나오는지?

2022-07-12 05:10 UTC, be-student commented on src/commom/utility/generateImageCode.ts
> +    const seq: number[] = Array.from(picks);
4,5,6 명째일 때 어떤 사람의 데이터는 안 들어갈 수도 있다는 부분이 문제가 될 수도 있을 거 같아서, 안 들어가는 사람은 없도록 해줄 수 있어?

2022-07-12 05:18 UTC, lcomment commented on src/commom/utility/generateImageCode.ts
> +  const kindOfImg: number[] = Array.from(set);
set 생성할 때 생성자 매개변수에 `정렬된 userList`를 넣어줘서 정렬된 형태로 잘 들어가

2022-07-12 05:18 UTC, lcomment commented on src/commom/utility/generateImageCode.ts
> +    const seq: number[] = Array.from(picks);
오키오키 이 부분 처리해서 다시 PR 보낼게

2022-07-13 13:42 UTC, be-student approved these changes

2022-07-13 13:42 UTC, be-student commented on src/commom/utility/generateImageCode.ts
> +  if(len==1 || set.size==1){
len부분은 불필요한 코드같아서 제거 부탁해

2022-07-13 13:42 UTC, merged